name: check-linter-and-installing-of-dels
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install reprository and check it
        uses: actions/checkout@v4      
      - run: make install
      - run: make lint